version: '3.8'

services:

  nginx:
    container_name: nginx
    image: nginx:0.1
    build:
      context: ./services/nginx/
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    volumes:
      - static-files:/var/www/django-files/static
    depends_on:
      - django
    networks:
      - transcendence-network

  django:
    container_name: django
    image: django:0.1
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    build:
      context: ./services/django
    volumes:
      - static-files:/app/transcendence/staticfiles
      - django-volume:/app/
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - transcendence-network

  postgres:
    container_name: postgres
    image: postgres:0.1
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    build:
      context: ./services/postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - transcendence-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  transcendence-network:
    name: transcendence-network

volumes:
  django-volume:
    name: django-volume
    driver: local
    driver_opts:
      type: none
      device: ./volumes/django/
      o: bind
  static-files:
    name: static-files
    driver: local
    driver_opts:
      type: none
      device: ./volumes/static
      o: bind
  postgres-volume:
    name: postgres-volume
    driver: local
    driver_opts:
      type: none
      device: ./volumes/postgres/
      o: bind